/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PageableObject } from './pageableObject';
import { SortObject } from './sortObject';
import { UnosiZaKorisnikaURasponuDTO } from './unosiZaKorisnikaURasponuDTO';


export interface PageUnosiZaKorisnikaURasponuDTO { 
    totalPages?: number;
    totalElements?: number;
    size?: number;
    content?: Array<UnosiZaKorisnikaURasponuDTO>;
    number?: number;
    sort?: Array<SortObject>;
    first?: boolean;
    last?: boolean;
    numberOfElements?: number;
    pageable?: PageableObject;
    empty?: boolean;
}

