/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface UnosiZaKorisnikaURasponuDTO { 
    idUnosNikotina?: number;
    kolicina?: number;
    idKorisnik?: number;
    idProizvod?: number;
    datum?: string;
    opisProizvoda?: string;
    nikotinSadrzaj?: number;
} 