export * from './korisnikController.service';
import { KorisnikControllerService } from './korisnikController.service';
export * from './ostvarioController.service';
import { OstvarioControllerService } from './ostvarioController.service';
export * from './postignuceController.service';
import { PostignuceControllerService } from './postignuceController.service';
export * from './postotnoPostignuceController.service';
import { PostotnoPostignuceControllerService } from './postotnoPostignuceController.service';
export * from './proizvodController.service';
import { ProizvodControllerService } from './proizvodController.service';
export * from './savjetController.service';
import { SavjetControllerService } from './savjetController.service';
export * from './tipProizvodaController.service';
import { TipProizvodaControllerService } from './tipProizvodaController.service';
export * from './unosKupnjeController.service';
import { UnosKupnjeControllerService } from './unosKupnjeController.service';
export * from './unosNikotinaController.service';
import { UnosNikotinaControllerService } from './unosNikotinaController.service';
export * from './vremenskoPostignuceController.service';
import { VremenskoPostignuceControllerService } from './vremenskoPostignuceController.service';
export const APIS = [KorisnikControllerService, OstvarioControllerService, PostignuceControllerService, PostotnoPostignuceControllerService, ProizvodControllerService, SavjetControllerService, TipProizvodaControllerService, UnosKupnjeControllerService, UnosNikotinaControllerService, VremenskoPostignuceControllerService];
